version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - zip function.zip index.js
      - aws lambda update-function-code \
          --function-name my-hello-lambda \
          --zip-file fileb://function.zip \
          --region ap-northeast-1

artifacts:
  files:
    - function.zip
